### PR TITLE
Fix welcome notice

### PR DESCRIPTION
**Pull request by image7**
Fix: #91

### CODE REVIEW

**Comment by ank1traj** [comment]
Hi @image7 

This issue has been fixed.

**Review by kapilpaul — APPROVED** [review]
LGTM. Nice work @image7

**Comment by ank1traj** [comment]
Hi @image7 

I checked this PR and come across an issue. On clicking on the `dismiss` the WP banner and rtBiz dashboard banner both become disappear. But we have to disappear rtBiz banner when we click on rtBiz `dismiss` and same for the WP banner. 

Right now, both dismiss is getting overlapped with each other.

Element for rtBiz dismiss - `<a class="welcome-panel-close" href="https://alivethunder.tastewp.com/wp-admin/admin.php?page=rtbiz-dashboard&amp;rtbizwelcome=0">Dismiss</a>`

Element for WP dismiss - `<a class="welcome-panel-close" href="https://alivethunder.tastewp.com/wp-admin/?welcome=0" aria-label="Dismiss the welcome panel">Dismiss</a>`

**Comment by pooja-muchandikar** [comment]
> https://github.com/rtCamp/rtbiz/pull/92#issuecomment-1028629352

This is [sorted](https://rtcamp.slack.com/archives/CQT8TKCJW/p1643868912114859?thread_ts=1643366236.648549&cid=CQT8TKCJW) hence merging the PR

**Pull request merged**
